/**
 * @file lib/db/src/schema/activity.ts
 * @description Schema for the **Activity Log** domain of the GRC data model.
 *
 * ## Purpose
 * The activity log provides an **append-only audit trail** of user-initiated actions
 * across the compliance platform.  It serves three primary roles:
 *
 * ### 1. PCI DSS Requirement 10 compliance (application-layer logging)
 * PCI DSS Requirement 10 mandates that all access to system components, cardholder
 * data, and audit trails must be logged with sufficient detail to reconstruct events.
 * The activity log satisfies this at the **application layer**:
 *  - Who performed the action (`actor`).
 *  - What was done (`action`).
 *  - What object was affected (`target`).
 *  - When it happened (`createdAt`).
 *  - Which entity's compliance data was involved (`entityCode`).
 *
 * ### 2. "Recent Activity" dashboard feed
 * The log powers the live activity feed shown on the main compliance dashboard,
 * giving stakeholders a real-time view of progress during active assessment cycles.
 *
 * ### 3. Forensic investigation support
 * In the event of a compliance incident, audit query, or data integrity question,
 * the log provides a tamper-resistant record of who changed what and when.
 *
 * ## Immutability guarantee
 * Records are **never updated or deleted** — new rows are only ever appended.
 * Application code and database roles must not issue UPDATE or DELETE against
 * this table.  Consider adding a PostgreSQL row-level security policy to enforce
 * this at the database level.
 *
 * ## Platform-level vs. entity-scoped entries
 * The `entityCode` column is nullable to support platform-level actions that are
 * not scoped to a single merchant:
 *  - Entity-scoped: `"alice approved EVR-2026-0042 for gopuff"`
 *    (`entityCode = "gopuff"`)
 *  - Platform-level: `"admin activated ISO 27001 framework"`
 *    (`entityCode = null`)
 *
 * ## Relationships
 *  - Many activity entries → one Entity (via `entityCode`, optional)
 *  - Activity entries reference other records descriptively via `target`
 *    (no FK enforcement — the target string remains readable even if the
 *     referenced record is later deleted)
 */

import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `activity_log` table — immutable audit trail of user actions in the GRC platform.
 *
 * Designed for high write volume during active assessment cycles (many evidence
 * request status changes, control finding updates, and approvals per day).
 * Reads are typically bounded by `entityCode` or a time window for the
 * dashboard feed, so consider indexing on `(entityCode, createdAt DESC)`.
 */
export const activityLogTable = pgTable("activity_log", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer (e.g. `crypto.randomUUID()`).
   * - Should never be reused — each log entry is a unique, immutable event.
   */
  id: text("id").primaryKey(),

  /**
   * Foreign key to `entities.code` (optional).
   *
   * - Constraints: nullable.
   * - When set, scopes this log entry to a specific merchant entity, enabling:
   *   - Per-entity activity feeds in the compliance dashboard.
   *   - Entity-filtered audit reports for QSA review.
   *   - Separation of audit trails between Gopuff, BevMo!, and Liquor Barn.
   * - Null for platform-level or cross-entity administrative actions (e.g.
   *   a framework being activated, a new user being provisioned).
   * - Note: no FK constraint is enforced here — if an entity is soft-deleted,
   *   its historical activity entries are retained with the original code.
   */
  entityCode: text("entity_code"),

  /**
   * Identifier of the user who performed the action.
   *
   * - Constraints: not null.
   * - Typically the authenticated user's username, display name, or email address
   *   as provided by the authentication system (e.g. `"alice@gopuff.com"`,
   *   `"John Smith"`).
   * - For system-generated events (e.g. automated escalation jobs), use a
   *   descriptive string like `"system"` or `"scheduler"`.
   * - PCI DSS Req 10.2.1 requires that individual user actions be attributable
   *   to a specific user ID; this column satisfies that requirement.
   */
  actor: text("actor").notNull(),

  /**
   * Short verb-phrase describing what was done.
   *
   * - Constraints: not null.
   * - Kept intentionally brief for display in the activity feed.
   * - Examples:
   *   - `"created evidence request"`
   *   - `"updated control finding"`
   *   - `"approved evidence"`
   *   - `"assigned vendor review"`
   *   - `"uploaded AoC document"`
   *   - `"marked policy as review-due"`
   *   - `"started assessment fieldwork"`
   * - Should be a past-tense human-readable phrase (not a technical event code)
   *   so it reads naturally in the dashboard feed: "{actor} {action} {target}".
   */
  action: text("action").notNull(),

  /**
   * Human-readable identifier of the object that was acted upon.
   *
   * - Constraints: not null.
   * - Stored as a **display string** rather than a foreign key so the log entry
   *   remains readable even if the referenced record is subsequently deleted
   *   or renamed.
   * - Examples:
   *   - `"EVR-2026-0042"` (evidence request code)
   *   - `"POL-007"` (policy code)
   *   - `"PCI-DSS Req 1.1.1"` (control reference)
   *   - `"Gopuff PCI DSS 4.0 Annual Assessment FY2025"` (assessment name)
   *   - `"Stripe"` (vendor name)
   * - The feed renders these as: `"{actor} {action} {target}"`, e.g.
   *   `"alice approved EVR-2026-0042"`.
   */
  target: text("target").notNull(),

  /**
   * Timestamp when this action occurred.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Stored with time zone to avoid ambiguity across server regions and DST changes.
   * - Used for chronological ordering of the activity feed (`ORDER BY created_at DESC`).
   * - PCI DSS Req 10.3 requires that timestamps be accurate and protected; database
   *   server time synchronisation (NTP) is assumed.
   * - Immutable after insert — the insert-time default captures the true event time;
   *   never back-fill or overwrite this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `activity_log` insert payloads.
 *
 * **Generated from** `activityLogTable` by `drizzle-zod`'s `createInsertSchema`.
 *
 * **Required fields** (caller must supply):
 *  - `id`     — UUID for this log entry.
 *  - `actor`  — username or display name of the user performing the action.
 *  - `action` — short verb-phrase (past tense) describing what was done.
 *  - `target` — human-readable identifier of the affected object.
 *
 * **Optional fields**:
 *  - `entityCode` — nullable; omit for platform-level actions not tied to a
 *                   specific merchant entity.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()` at insert time.
 *                  **Do not allow callers to supply a custom timestamp** — this
 *                  would undermine the integrity of the audit log.
 *
 * @example
 * ```ts
 * // Log an evidence approval action
 * const entry = insertActivitySchema.parse({
 *   id: crypto.randomUUID(),
 *   entityCode: "gopuff",
 *   actor: "alice@gopuff.com",
 *   action: "approved evidence",
 *   target: "EVR-2026-0042",
 * });
 * await db.insert(activityLogTable).values(entry);
 *
 * // Log a platform-level action (no entity)
 * const platformEntry = insertActivitySchema.parse({
 *   id: crypto.randomUUID(),
 *   actor: "admin@gopuff.com",
 *   action: "activated framework",
 *   target: "ISO 27001",
 * });
 * await db.insert(activityLogTable).values(platformEntry);
 * ```
 */
export const insertActivitySchema = createInsertSchema(activityLogTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertActivity` — shape of the object required to insert a new activity log entry.
 *
 * Inferred from `insertActivitySchema` (the Zod insert schema).
 *
 * **Usage**: audit logging helpers, API route middleware, event handlers that
 * record user actions after successful mutations.
 *
 * @example
 * ```ts
 * /**
 *  * Logs a user action to the activity log.
 *  * @param entry - The activity entry to record.
 *  * @returns The newly created ActivityEntry row.
 *  *\/
 * async function logActivity(entry: InsertActivity): Promise<ActivityEntry> {
 *   const validated = insertActivitySchema.parse(entry);
 *   const [row] = await db.insert(activityLogTable).values(validated).returning();
 *   return row;
 * }
 * ```
 */
export type InsertActivity = z.infer<typeof insertActivitySchema>;

/**
 * `ActivityEntry` — full shape of a row returned by a SELECT on `activityLogTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, activity feed components, audit report exports,
 * forensic investigation queries.
 *
 * @example
 * ```ts
 * // Fetch the 20 most recent actions for the BevMo! entity
 * const feed: ActivityEntry[] = await db
 *   .select()
 *   .from(activityLogTable)
 *   .where(eq(activityLogTable.entityCode, "bevmo"))
 *   .orderBy(desc(activityLogTable.createdAt))
 *   .limit(20);
 * ```
 */
export type ActivityEntry = typeof activityLogTable.$inferSelect;
