/**
 * @file lib/db/src/schema/aocs.ts
 * @description Schema for the **Attestations of Compliance (AoC)** domain of the GRC data model.
 *
 * ## What is an Attestation of Compliance?
 * An Attestation of Compliance (AoC) is the formal certificate issued by a Qualified
 * Security Assessor (QSA) — or signed by the merchant itself for SAQ assessments —
 * upon successful completion of a PCI DSS assessment.  It is the primary artefact
 * that proves PCI DSS compliance to:
 *  - **Acquiring banks**: who are contractually required to maintain their merchant
 *    portfolio's compliance.
 *  - **Card brands** (Visa, Mastercard, Amex, Discover): who set the compliance rules
 *    and can levy fines or revoke card acceptance rights for non-compliance.
 *  - **Business partners and auditors**: who may request proof of compliance during
 *    due diligence.
 *
 * ## AoC vs. ROC
 *  - A **Report on Compliance (ROC)** is the detailed technical assessment report
 *    produced by the QSA.  It is typically a confidential document.
 *  - An **AoC** is the short cover document (usually 2–4 pages) extracted from the
 *    ROC and shared with acquiring banks.  This table stores the AoC.
 *
 * ## Lifecycle / status
 * ```
 * draft → current → superseded
 * ```
 *  1. `draft`      — assessment complete but formal AoC not yet signed.
 *  2. `current`    — the active, valid AoC.  An entity should have exactly one
 *                    `current` AoC per framework at any time.
 *  3. `superseded` — replaced by a newer AoC after a subsequent assessment cycle.
 *                    Retained for the audit history.
 *
 * ## AoC expiry and renewal
 * PCI DSS AoCs are valid for 12 months.  The platform uses `expiresDate` to:
 *  - Surface "expiring soon" alerts in the compliance dashboard.
 *  - Drive the creation of the next assessment engagement.
 *  - Notify the entity's compliance contact when the AoC has expired.
 *
 * ## Relationships
 *  - Many AoCs → one Entity    (via `entityCode`)
 *  - Many AoCs → one Framework (via `frameworkCode`)
 *  - Optionally linked to an uploaded file (via `filename` / `filePath`)
 */

import { pgTable, text, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `aocs` table — one row per Attestation of Compliance document.
 *
 * Multiple historical AoC rows may exist for the same entity+framework
 * combination (one per assessment year); only the row with `status = "current"`
 * is the live certificate.
 */
export const aocsTable = pgTable("aocs", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer.
   */
  id: text("id").primaryKey(),

  /**
   * Foreign key to `entities.code`.
   *
   * - Constraints: not null.
   * - Identifies which merchant entity this AoC certifies compliance for.
   * - A single acquiring bank may request AoCs for all entities (Gopuff, BevMo!,
   *   Liquor Barn) separately because each has its own CDE boundary.
   */
  entityCode: text("entity_code").notNull(),

  /**
   * Short code of the framework this AoC attests compliance to.
   *
   * - Constraints: not null.
   * - Examples: `"PCI-DSS"`, `"SOC2"` (though AoCs are most commonly PCI DSS).
   * - Must match a value in `frameworks.code`.
   */
  frameworkCode: text("framework_code").notNull(),

  /**
   * Full framework display name, denormalised for read queries.
   *
   * - Constraints: nullable.
   * - Examples: `"PCI DSS 4.0"`, `"SOC 2 Type II"`.
   * - Stored to avoid a join when rendering the AoC detail view.
   */
  frameworkName: text("framework_name"),

  /**
   * Descriptive title for this AoC record as displayed in the UI.
   *
   * - Constraints: not null.
   * - Examples: `"PCI DSS AoC – Gopuff FY2025"`, `"BevMo! PCI DSS 4.0 AoC 2024"`.
   * - Should include the entity name, framework, and year for easy identification
   *   when browsing the AoC history.
   */
  title: text("title").notNull(),

  /**
   * Lifecycle status of this AoC within the entity's compliance history.
   *
   * - Constraints: not null, defaults to `"current"`.
   * - Allowed values:
   *   - `"current"`    — the active, valid AoC.  At most one `current` AoC should
   *                      exist per entity+framework combination at any point in time.
   *   - `"superseded"` — replaced by a newer AoC after a subsequent assessment.
   *                      The old row is kept for audit trail and comparison purposes.
   *   - `"draft"`      — the assessment fieldwork is complete but the QSA has not yet
   *                      signed and issued the formal AoC document.
   */
  status: text("status").notNull().default("current"), // current|superseded|draft

  /**
   * Name of the QSA firm that conducted the assessment and countersigned this AoC.
   *
   * - Constraints: nullable (null for SAQ self-assessments not requiring a QSA).
   * - A QSA must be listed on the PCI SSC's Qualified Security Assessors roster.
   * - Examples: `"Coalfire"`, `"Verizon Business"`, `"Trustwave"`, `"SecurityMetrics"`.
   */
  qsaCompany: text("qsa_company"),

  /**
   * Name of the individual QSA who signed the Attestation of Compliance.
   *
   * - Constraints: nullable.
   * - The lead QSA is the named individual whose certification is staked on the
   *   accuracy of the compliance attestation.
   * - Examples: `"John Smith, QSA"`.
   */
  qsaLead: text("qsa_lead"),

  /**
   * ISO-8601 date (YYYY-MM-DD) when this AoC was formally issued and signed.
   *
   * - Constraints: nullable (draft AoCs may not have an issuance date yet).
   * - This is the date that appears on the AoC document itself and is reported
   *   to the acquiring bank.
   */
  issuedDate: text("issued_date"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) when this AoC expires.
   *
   * - Constraints: nullable (computed from `issuedDate` + 12 months, but stored
   *   explicitly to support edge cases such as QSA-granted extensions).
   * - After this date the entity's AoC is no longer valid; the acquiring bank
   *   may flag the merchant as non-compliant until a new assessment is completed.
   * - Used by the platform to generate renewal alerts at configurable lead times
   *   (e.g. 90-day, 60-day, 30-day warnings).
   */
  expiresDate: text("expires_date"), // YYYY-MM-DD

  /**
   * Fiscal or assessment period this AoC covers.
   *
   * - Constraints: nullable.
   * - Examples: `"FY2025"`, `"Q3 2024"`, `"CY2024"`.
   * - Provides a human-readable period label that is distinct from the exact
   *   issuance / expiry date range and maps to internal reporting cycles.
   */
  period: text("period"), // "FY2025"

  /**
   * Overall assessment result or compliance determination as recorded on the AoC.
   *
   * - Constraints: nullable.
   * - Common values:
   *   - `"Compliant"` — all requirements were met; no unresolved findings.
   *   - `"Compliant with CCW"` — compliant, but one or more Compensating Control
   *     Worksheets were required for controls that could not be met as written.
   *   - `"Non-Compliant"` — one or more requirements were not met at assessment time.
   * - An AoC with `"Non-Compliant"` result cannot be submitted to an acquiring bank
   *   as proof of compliance.
   */
  result: text("result"),

  /**
   * Number of individual PCI DSS controls (sub-requirements) covered by this assessment.
   *
   * - Constraints: nullable (informational; populated from ROC metadata).
   * - Useful for comparing the scope of successive assessments — a reduced scope
   *   assessment will have fewer controls covered than a full ROC.
   */
  controlsCovered: integer("controls_covered"),

  /**
   * Count of open findings or exceptions documented in the assessment at issuance time.
   *
   * - Constraints: nullable.
   * - `0` indicates fully compliant with no exceptions, CCWs, or compensating controls.
   * - A non-zero value means some requirements were not fully met; findings should
   *   be tracked in the controls table and associated evidence requests.
   */
  findings: integer("findings"),

  /**
   * Original filename of the uploaded AoC PDF document.
   *
   * - Constraints: nullable (not all AoC records will have a file uploaded).
   * - Examples: `"gopuff-aoc-fy2025.pdf"`, `"bevmo-pci-dss-4-aoc-2024.pdf"`.
   * - Displayed in the UI to indicate a file is available for download.
   */
  filename: text("filename"),

  /**
   * Server-side file path or storage key where the AoC document is persisted.
   *
   * - Constraints: nullable.
   * - May be a local file system path (e.g. `"uploads/aocs/gopuff-aoc-fy2025.pdf"`)
   *   or an object storage key (e.g. an S3 key).
   * - Used by the file-download endpoint to serve the document.
   * - `null` when no file has been uploaded yet.
   */
  filePath: text("file_path"),

  /**
   * Free-text notes about this AoC record.
   *
   * - Constraints: nullable.
   * - May document scope limitations, context about specific findings, or
   *   rationale for any Compensating Control Worksheets.
   * - Visible to the compliance team but not shared externally in reports.
   */
  notes: text("notes"),

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `aocs` insert payloads sent via the API.
 *
 * **Generated from** `aocsTable` by `drizzle-zod`'s `createInsertSchema`.
 *
 * **Required fields** (caller must supply):
 *  - `id`            — UUID primary key.
 *  - `entityCode`    — FK to `entities.code`.
 *  - `frameworkCode` — short framework code (e.g. `"PCI-DSS"`).
 *  - `title`         — descriptive AoC title.
 *
 * **Optional / defaulted fields**:
 *  - `status`          — defaults to `"current"` if omitted.
 *  - `frameworkName`   — nullable; provide for denormalised display.
 *  - `qsaCompany`      — nullable; omit for SAQ self-assessments.
 *  - `qsaLead`         — nullable.
 *  - `issuedDate`      — nullable; set when the QSA signs the document.
 *  - `expiresDate`     — nullable; typically `issuedDate` + 12 months.
 *  - `period`          — nullable; provide a fiscal year label (e.g. `"FY2025"`).
 *  - `result`          — nullable; set from the final ROC/AoC outcome.
 *  - `controlsCovered` — nullable; informational count.
 *  - `findings`        — nullable; count of open findings at issuance.
 *  - `filename`        — nullable; set after file upload.
 *  - `filePath`        — nullable; set after file upload.
 *  - `notes`           — nullable.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertAocSchema.parse({
 *   id: crypto.randomUUID(),
 *   entityCode: "gopuff",
 *   frameworkCode: "PCI-DSS",
 *   frameworkName: "PCI DSS 4.0",
 *   title: "PCI DSS AoC – Gopuff FY2025",
 *   status: "current",
 *   qsaCompany: "Coalfire",
 *   issuedDate: "2025-03-15",
 *   expiresDate: "2026-03-14",
 *   period: "FY2025",
 *   result: "Compliant",
 * });
 * await db.insert(aocsTable).values(payload);
 * ```
 */
export const insertAocSchema = createInsertSchema(aocsTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertAoc` — shape of the object required to insert a new AoC row.
 *
 * Inferred from `insertAocSchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, AoC upload endpoints, assessment
 * close-out workflows.
 *
 * @example
 * ```ts
 * async function issueAoc(body: InsertAoc): Promise<Aoc> {
 *   const validated = insertAocSchema.parse(body);
 *   const [row] = await db.insert(aocsTable).values(validated).returning();
 *   return row;
 * }
 * ```
 */
export type InsertAoc = z.infer<typeof insertAocSchema>;

/**
 * `Aoc` — full shape of a row returned by a SELECT on `aocsTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, compliance dashboard components, AoC history views,
 * certificate download endpoints.
 *
 * @example
 * ```ts
 * const currentAoc: Aoc | undefined = await db
 *   .select()
 *   .from(aocsTable)
 *   .where(
 *     and(
 *       eq(aocsTable.entityCode, "gopuff"),
 *       eq(aocsTable.frameworkCode, "PCI-DSS"),
 *       eq(aocsTable.status, "current"),
 *     ),
 *   )
 *   .then((rows) => rows[0]);
 * ```
 */
export type Aoc = typeof aocsTable.$inferSelect;
