/**
 * @file lib/db/src/schema/assessments.ts
 * @description Schema for the **Assessments** domain of the GRC data model.
 *
 * ## What is an Assessment?
 * An "assessment" represents a formal audit engagement — a bounded time period
 * during which a QSA or internal compliance team tests controls, gathers evidence,
 * and ultimately produces a compliance artefact:
 *  - **PCI DSS Level 1**: a Report on Compliance (ROC) and Attestation of Compliance (AoC).
 *  - **PCI DSS Level 2–4**: a Self-Assessment Questionnaire (SAQ) and AoC.
 *  - **SOC 2**: a SOC 2 Type II report.
 *  - **Internal readiness review**: a gap analysis without a formal external output.
 *
 * ## Assessment lifecycle
 * ```
 * planning → fieldwork → reporting → closed
 * ```
 *  1. **planning**  — scope, schedule, and assessor assignment are being agreed.
 *                     Evidence request templates are prepared; entities are notified.
 *  2. **fieldwork** — active control testing phase; evidence requests are raised and
 *                     control owners are gathering artefacts.  This is the most
 *                     operationally intensive phase.
 *  3. **reporting** — fieldwork is complete; the QSA is drafting the ROC / AoC.
 *                     The entity reviews findings and remediation is finalised.
 *  4. **closed**    — the compliance report has been issued and the AoC (if
 *                     applicable) has been filed with the acquiring bank.
 *
 * ## Planned vs. actual dates
 * The schema stores both planned (`plannedStart`, `plannedEnd`) and actual
 * (`actualStart`, `actualEnd`) dates to support:
 *  - Variance analysis: how often does fieldwork finish on schedule?
 *  - SLA tracking: are evidence requests being fulfilled within the planned window?
 *  - Historical reporting: when was the entity actually compliant?
 *
 * ## Internal vs. QSA-led assessments
 * The `qsaCompany` and `leadAssessor` fields are nullable to support internal
 * readiness reviews (first-party assessments) that do not require an external QSA.
 * For Level-1 PCI DSS assessments, both must be populated.
 *
 * ## Relationships
 *  - Many assessments → one Entity     (via `entityCode`)
 *  - Many assessments → one Framework  (via `frameworkId` / `frameworkCode`)
 *  - One assessment   → many EvidenceRequests (via `evidenceRequests.assessmentId`)
 *  - One assessment   → one AoC (logical link via `entityCode` + `period`, not enforced by FK)
 */

import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `assessments` table — one row per formal compliance assessment engagement.
 *
 * A single entity typically has one assessment per framework per year.  Multiple
 * active assessments can coexist for the same entity if different frameworks
 * are being assessed in parallel (e.g. PCI DSS and SOC 2 running concurrently).
 */
export const assessmentsTable = pgTable("assessments", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer (e.g. `crypto.randomUUID()`).
   */
  id: text("id").primaryKey(),

  /**
   * Foreign key to `entities.code`.
   *
   * - Constraints: not null.
   * - Identifies which merchant entity is being assessed.
   * - Evidence requests linked to this assessment will share this `entityCode`,
   *   ensuring artefacts are attributed to the correct merchant.
   */
  entityCode: text("entity_code").notNull(),

  /**
   * Foreign key to `frameworks.id`.
   *
   * - Constraints: not null.
   * - Identifies the compliance framework being assessed (e.g. PCI DSS 4.0, SOC 2).
   * - Determines which controls are in scope and which evidence templates to apply.
   */
  frameworkId: text("framework_id").notNull(),

  /**
   * Denormalised short code of the parent framework (e.g. `"PCI-DSS"`, `"SOC2"`).
   *
   * - Constraints: not null.
   * - Stored redundantly to avoid joins on filtered list queries
   *   (e.g. "show all active PCI-DSS assessments").
   * - Must stay in sync with `frameworks.code` for the referenced framework.
   */
  frameworkCode: text("framework_code").notNull(),

  /**
   * Full framework display name, denormalised for read queries.
   *
   * - Constraints: nullable.
   * - Examples: `"PCI DSS 4.0"`, `"SOC 2 Type II"`.
   * - Stored to avoid a join when rendering assessment cards in the dashboard.
   */
  frameworkName: text("framework_name"),

  /**
   * Human-readable name for this assessment engagement.
   *
   * - Constraints: not null.
   * - Examples: `"Gopuff PCI DSS 4.0 Annual Assessment FY2025"`,
   *   `"BevMo! Internal PCI Readiness Review Q1 2026"`.
   * - Used as the primary identifier in the assessment list and email notifications.
   */
  name: text("name").notNull(),

  /**
   * Name of the Qualified Security Assessor company conducting this engagement.
   *
   * - Constraints: nullable.
   * - Null for internal (first-party) readiness reviews not requiring a certified QSA.
   * - For Level-1 PCI DSS assessments, this must be populated with the name of a
   *   PCI SSC-listed QSA company.
   * - Examples: `"Coalfire"`, `"Verizon Business"`, `"Trustwave"`.
   */
  qsaCompany: text("qsa_company"),

  /**
   * Name of the lead assessor individual managing fieldwork and reporting.
   *
   * - Constraints: nullable.
   * - For QSA-led assessments: the individual QSA whose certification covers the
   *   assessment (e.g. `"John Smith, QSA"`).
   * - For internal reviews: the internal audit manager or compliance lead.
   * - Used for contact routing and named responsibility in the assessment record.
   */
  leadAssessor: text("lead_assessor"),

  /**
   * ISO-8601 date (YYYY-MM-DD) when assessment fieldwork is scheduled to begin.
   *
   * - Constraints: nullable (may not be set during initial planning stage).
   * - Drives the assessment timeline view and resource planning.
   * - Evidence request due dates are typically anchored to this date.
   */
  plannedStart: text("planned_start"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) when the assessment (including reporting) is
   * scheduled to be completed and the AoC issued.
   *
   * - Constraints: nullable.
   * - Acquiring banks may set a deadline by which the new AoC must be delivered;
   *   this field captures that contractual commitment.
   */
  plannedEnd: text("planned_end"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) when fieldwork actually commenced.
   *
   * - Constraints: nullable; set when the assessment transitions to `"fieldwork"`.
   * - May differ from `plannedStart` due to scheduling changes, scope adjustments,
   *   or delays in QSA availability.
   * - Used in variance analysis (planned vs. actual start date).
   */
  actualStart: text("actual_start"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) when the assessment was actually completed
   * (i.e. the AoC was issued and filed).
   *
   * - Constraints: nullable; set when the assessment transitions to `"closed"`.
   * - Null for any assessment not yet in the `closed` status.
   * - Used to calculate total assessment cycle duration and time-to-close metrics.
   */
  actualEnd: text("actual_end"), // YYYY-MM-DD

  /**
   * Current lifecycle stage of the assessment engagement.
   *
   * - Constraints: not null, defaults to `"planning"`.
   * - Allowed values (see lifecycle diagram at the top of this file):
   *   - `"planning"`  — scope and schedule are being defined; QSA is being contracted.
   *   - `"fieldwork"` — active evidence gathering and control testing is under way.
   *   - `"reporting"` — fieldwork complete; QSA is drafting the final report / AoC.
   *   - `"closed"`    — assessment complete; report and AoC issued to acquiring bank.
   * - Status transitions are one-directional: planning → fieldwork → reporting → closed.
   */
  status: text("status").notNull().default("planning"), // planning|fieldwork|reporting|closed

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `assessments` insert payloads sent via the API.
 *
 * **Generated from** `assessmentsTable` by `drizzle-zod`'s `createInsertSchema`.
 *
 * **Required fields** (caller must supply):
 *  - `id`            — UUID primary key.
 *  - `entityCode`    — FK to `entities.code`.
 *  - `frameworkId`   — FK to `frameworks.id`.
 *  - `frameworkCode` — denormalised framework code (e.g. `"PCI-DSS"`).
 *  - `name`          — human-readable engagement name.
 *
 * **Optional / defaulted fields**:
 *  - `status`        — defaults to `"planning"` if omitted.
 *  - `frameworkName` — nullable; provide for denormalised display.
 *  - `qsaCompany`    — nullable; omit for internal assessments.
 *  - `leadAssessor`  — nullable.
 *  - `plannedStart`  — nullable; set once scheduling is agreed.
 *  - `plannedEnd`    — nullable; set once scheduling is agreed.
 *  - `actualStart`   — nullable; set when fieldwork begins.
 *  - `actualEnd`     — nullable; set when assessment closes.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertAssessmentSchema.parse({
 *   id: crypto.randomUUID(),
 *   entityCode: "gopuff",
 *   frameworkId: "pci-dss-4",
 *   frameworkCode: "PCI-DSS",
 *   frameworkName: "PCI DSS 4.0",
 *   name: "Gopuff PCI DSS 4.0 Annual Assessment FY2025",
 *   qsaCompany: "Coalfire",
 *   plannedStart: "2025-01-15",
 *   plannedEnd: "2025-03-31",
 * });
 * await db.insert(assessmentsTable).values(payload);
 * ```
 */
export const insertAssessmentSchema = createInsertSchema(assessmentsTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertAssessment` — shape of the object required to insert a new assessment row.
 *
 * Inferred from `insertAssessmentSchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, assessment creation endpoints, seed scripts.
 *
 * @example
 * ```ts
 * async function createAssessment(body: InsertAssessment): Promise<Assessment> {
 *   const validated = insertAssessmentSchema.parse(body);
 *   const [row] = await db.insert(assessmentsTable).values(validated).returning();
 *   return row;
 * }
 * ```
 */
export type InsertAssessment = z.infer<typeof insertAssessmentSchema>;

/**
 * `Assessment` — full shape of a row returned by a SELECT on `assessmentsTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, assessment dashboard components, evidence request
 * management forms (to show which assessment an EVR belongs to).
 *
 * @example
 * ```ts
 * const activeAssessments: Assessment[] = await db
 *   .select()
 *   .from(assessmentsTable)
 *   .where(
 *     inArray(assessmentsTable.status, ["planning", "fieldwork", "reporting"]),
 *   );
 * ```
 */
export type Assessment = typeof assessmentsTable.$inferSelect;
