/**
 * @file lib/db/src/schema/controls.ts
 * @description Schema for the **Controls** domain of the GRC data model.
 *
 * ## What is a Control?
 * A "control" is an individual requirement or safeguard drawn from a compliance
 * framework (e.g. PCI DSS Requirement 1.1.1 or SOC 2 Common Criteria CC6.1).
 *
 * Controls are the **atomic unit of compliance evidence**: each one must be
 * tested during an assessment, assigned a finding status, and backed by at least
 * one approved evidence artefact before the QSA can sign off on the AoC.
 *
 * ## Global vs. entity-scoped controls
 * Controls can be:
 *  - **Global** (`entityCode = null`): applies to all entities under the framework.
 *    Most PCI DSS requirements fall into this category.
 *  - **Entity-scoped** (`entityCode = "bevmo"`): applies only to a specific merchant.
 *    Used when an entity's CDE is unique — e.g. physical card-present terminal
 *    requirements only apply to BevMo! and Liquor Barn, not to the e-commerce-only
 *    Gopuff brand.
 *
 * ## Finding lifecycle
 * During fieldwork an assessor reviews each in-scope control and assigns a
 * finding.  The finding drives whether an AoC can be issued:
 *  1. `not-tested`     — default state; fieldwork not yet begun for this control.
 *  2. `in-place`       — control is fully implemented and effective; no issues found.
 *  3. `not-applicable` — control does not apply (documented exception / compensating
 *                        control worksheet filed with the QSA).
 *  4. `not-in-place`   — control tested and found deficient; a remediation action is
 *                        required before the AoC can be issued.
 *
 * ## Relationships
 *  - Many controls → one Framework     (via `frameworkId` / `frameworkCode`)
 *  - One control   → many EvidenceRequests (via `evidenceRequests.controlId`)
 *  - Many controls → one Entity, or null   (via `entityCode`)
 */

import { pgTable, text, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `controls` table — one row per individual framework requirement tracked by the platform.
 *
 * Rows are typically bulk-inserted when a new framework is activated in the system
 * (e.g. all 250+ PCI DSS 4.0 sub-requirements are seeded at once).  They are then
 * updated by assessors as fieldwork progresses.
 */
export const controlsTable = pgTable("controls", {
  /**
   * UUID primary key for this control instance.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer (e.g. `crypto.randomUUID()`).
   * - Stable across re-imports of the same framework version.
   */
  id: text("id").primaryKey(),

  /**
   * Foreign key to `frameworks.id`.
   *
   * - Constraints: not null.
   * - Links this control back to its parent compliance framework record.
   * - Used in joins when loading controls alongside framework metadata.
   */
  frameworkId: text("framework_id").notNull(),

  /**
   * Denormalised short code of the parent framework (e.g. `"PCI-DSS"`, `"SOC2"`).
   *
   * - Constraints: not null.
   * - Stored redundantly to avoid joins on the most common list and filter
   *   queries (e.g. "show all PCI-DSS controls with `finding = not-in-place`").
   * - Must match `frameworks.code` for the referenced framework.
   */
  frameworkCode: text("framework_code").notNull(),

  /**
   * Human-readable control reference number as defined by the framework publisher.
   *
   * - Constraints: not null.
   * - Examples:
   *   - PCI DSS: `"1.1.1"`, `"6.4.3"`, `"12.10.1"`
   *   - SOC 2:   `"CC6.1"`, `"CC7.2"`, `"A1.1"`
   *   - ISO 27001: `"A.9.4.2"`, `"A.12.6.1"`
   * - Used to cross-reference controls with evidence requests and the source
   *   framework documentation.
   */
  ref: text("ref").notNull(), // e.g. "1.1.1", "CC6.1"

  /**
   * Short title of the control as published in the framework documentation.
   *
   * - Constraints: not null.
   * - Example: `"All security policies, standards, and procedures are established,
   *   implemented, and maintained"` (PCI DSS 12.1.1).
   * - Used as the display label in control lists, evidence request forms,
   *   and assessment dashboards.
   */
  title: text("title").notNull(),

  /**
   * Full requirement text or description providing implementation guidance.
   *
   * - Constraints: nullable (short/alias controls may omit the verbose description).
   * - Contains the detailed, normative language from the framework publication.
   * - Displayed in the control detail panel to help assessors and control owners
   *   understand exactly what must be evidenced.
   */
  description: text("description"),

  /**
   * Top-level domain (grouping) this control belongs to within its framework.
   *
   * - Constraints: not null.
   * - In PCI DSS, domains map to the 12 high-level requirements:
   *   1. "Build and Maintain a Secure Network and Systems"
   *   2. "Protect Account Data"
   *   3. "Maintain a Vulnerability Management Program"
   *   4. "Implement Strong Access Control Measures"
   *   5. "Regularly Monitor and Test Networks"
   *   6. "Maintain an Information Security Policy"
   *   (Plus related sub-goals and appendices in v4.0)
   * - Used for grouped display and progress reporting per domain.
   */
  domain: text("domain").notNull(),

  /**
   * Numeric ordering key for the domain.
   *
   * - Constraints: not null, defaults to `1`.
   * - Enables correct sorted display of domains without relying on a string sort
   *   (which would mis-order `"10"` before `"2"`).
   * - Application code should populate this from the framework's official domain
   *   numbering (e.g. PCI DSS domain 1 = `1`, domain 12 = `12`).
   */
  domainNumber: integer("domain_number").notNull().default(1),

  /**
   * Foreign key to `entities.code`, scoping this control to a single merchant entity.
   *
   * - Constraints: nullable.
   * - `null` — control applies universally to **all** entities under this framework.
   * - `"bevmo"` — control applies exclusively to BevMo! (e.g. physical terminal reqs).
   * - Entity-scoped controls allow the platform to reflect real-world differences in
   *   CDE scope between brands without duplicating the entire control library.
   */
  entityCode: text("entity_code"), // null = applies to all entities

  /**
   * Assessment finding status for this control, populated during fieldwork.
   *
   * - Constraints: nullable (null = not yet assessed; equivalent to `"not-tested"`).
   * - Allowed values:
   *   - `"in-place"`       — control is fully implemented and operating effectively.
   *                          The QSA has reviewed evidence and is satisfied.
   *   - `"not-applicable"` — control does not apply to this entity's specific environment.
   *                          An exemption rationale must be documented and signed off.
   *   - `"not-tested"`     — control is within scope but has not yet been evaluated
   *                          during the current assessment cycle.
   *   - `"not-in-place"`   — control was tested and found to be deficient (a gap /
   *                          finding).  A remediation plan is required; the AoC cannot
   *                          be issued until this is resolved or a CCW is approved.
   */
  finding: text("finding"), // in-place|not-applicable|not-tested|not-in-place

  /**
   * Free-text assessor notes or remediation guidance.
   *
   * - Constraints: nullable.
   * - For `"not-in-place"` findings: documents the gap, root cause, and
   *   remediation steps agreed with the entity.
   * - For `"not-applicable"` findings: records the justification for the exemption.
   * - For `"in-place"` findings: may include brief notes about testing methodology
   *   or evidence reviewed.
   */
  notes: text("notes"),

  /**
   * ISO-8601 date-time string recording when this control was most recently tested.
   *
   * - Constraints: nullable (null if the control has never been tested).
   * - Format: YYYY-MM-DD or full ISO timestamp (e.g. `"2025-03-15"`).
   * - Used to calculate "staleness" of controls and flag ones that haven't
   *   been reviewed within the assessment window.
   */
  lastTestedAt: text("last_tested_at"),

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `controls` insert payloads sent via the API.
 *
 * **Generated from** `controlsTable` by `drizzle-zod`'s `createInsertSchema`.
 *
 * **Required fields** (caller must supply):
 *  - `id`            — UUID primary key.
 *  - `frameworkId`   — FK to `frameworks.id`.
 *  - `frameworkCode` — denormalised framework code (e.g. `"PCI-DSS"`).
 *  - `ref`           — control reference number (e.g. `"1.1.1"`).
 *  - `title`         — short control title.
 *  - `domain`        — domain name grouping this control.
 *
 * **Optional / defaulted fields**:
 *  - `domainNumber` — defaults to `1`; should be set to the correct domain ordinal.
 *  - `entityCode`   — nullable; omit for global controls.
 *  - `description`  — nullable; omit if not available.
 *  - `finding`      — nullable; omit on initial import (assessed later).
 *  - `notes`        — nullable; omit if none.
 *  - `lastTestedAt` — nullable; omit until fieldwork begins.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertControlSchema.parse({
 *   id: crypto.randomUUID(),
 *   frameworkId: "pci-dss-4",
 *   frameworkCode: "PCI-DSS",
 *   ref: "1.1.1",
 *   title: "Network security controls are implemented",
 *   domain: "Build and Maintain a Secure Network",
 *   domainNumber: 1,
 * });
 * await db.insert(controlsTable).values(payload);
 * ```
 */
export const insertControlSchema = createInsertSchema(controlsTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertControl` — shape of the object required to insert a new control row.
 *
 * Inferred from `insertControlSchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, framework seed scripts, bulk import tools.
 *
 * @example
 * ```ts
 * async function seedControls(controls: InsertControl[]) {
 *   await db.insert(controlsTable).values(controls);
 * }
 * ```
 */
export type InsertControl = z.infer<typeof insertControlSchema>;

/**
 * `Control` — full shape of a row returned by a SELECT on `controlsTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, assessment dashboard state, evidence request forms.
 *
 * @example
 * ```ts
 * const controls: Control[] = await db
 *   .select()
 *   .from(controlsTable)
 *   .where(eq(controlsTable.frameworkCode, "PCI-DSS"));
 *
 * const notInPlace = controls.filter((c) => c.finding === "not-in-place");
 * ```
 */
export type Control = typeof controlsTable.$inferSelect;
