/**
 * @file lib/db/src/schema/evidence.ts
 * @description Schema for the **Evidence Requests** domain of the GRC data model.
 *
 * ## What is an Evidence Request?
 * An evidence request (EVR) is the primary **workflow unit** for gathering audit
 * artefacts during an assessment.  When the QSA or internal compliance team tests
 * a control, they raise an evidence request asking a control owner or system team
 * to provide documentation that demonstrates the control is operating effectively.
 *
 * Examples of evidence artefacts:
 *  - Firewall rule exports (PCI DSS Req 1)
 *  - Penetration test executive summary reports (PCI DSS Req 11.4)
 *  - Screenshots of quarterly user access reviews (PCI DSS Req 7.2)
 *  - Vendor security certifications (PCI DSS Req 12.8)
 *  - Encryption configuration screenshots (PCI DSS Req 3, 4)
 *
 * ## Workflow lifecycle
 * ```
 * requested → in-progress → submitted → approved
 *                                    ↘ rejected → (back to in-progress)
 * ```
 *  1. `requested`   — request raised, awaiting pick-up by the assignee.
 *  2. `in-progress` — assignee is actively gathering the evidence.
 *  3. `submitted`   — artefact uploaded; awaiting reviewer approval.
 *  4. `approved`    — reviewer accepted; evidence is sufficient for the control finding.
 *  5. `rejected`    — reviewer found evidence insufficient; assignee must re-submit.
 *
 * ## Ad-hoc vs. assessment-linked requests
 * An EVR may be:
 *  - **Assessment-linked** (`assessmentId` is set): raised during a formal
 *    assessment engagement, contributing to the final ROC/AoC.
 *  - **Ad-hoc** (`assessmentId = null`): raised outside a scheduled cycle, e.g.
 *    for a targeted internal review, an incident investigation, or a regulator
 *    enquiry.
 *
 * ## Relationships
 *  - Many evidence requests → one Assessment  (via `assessmentId`, optional)
 *  - Many evidence requests → one Control     (via `controlId` / `controlRef`, optional)
 *  - Many evidence requests → one Entity      (via `entityCode`)
 *  - Many evidence requests → one Framework   (via `frameworkCode`)
 */

import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `evidence_requests` table — one row per evidence item requested from control owners.
 *
 * This is the most actively written table in the system during an assessment cycle:
 * rows are inserted when requests are raised, and updated each time the status,
 * assignee, or due date changes.
 */
export const evidenceRequestsTable = pgTable("evidence_requests", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer (e.g. `crypto.randomUUID()`).
   */
  id: text("id").primaryKey(),

  /**
   * Human-readable sequential identifier displayed in the UI and email notifications.
   *
   * - Constraints: not null, unique.
   * - Format: `EVR-YYYY-NNNN` e.g. `"EVR-2026-0001"`.
   * - Stakeholders use this code to reference specific requests in Slack, email,
   *   and the audit trail without needing the raw UUID.
   * - The application is responsible for generating these sequentially; the
   *   database only enforces uniqueness.
   */
  code: text("code").notNull().unique(), // EVR-2026-0001

  /**
   * Foreign key to `assessments.id` (optional).
   *
   * - Constraints: nullable.
   * - When set, links this evidence request to a formal assessment engagement,
   *   allowing the assessment progress dashboard to aggregate evidence by status.
   * - Null for ad-hoc requests raised outside a scheduled assessment cycle.
   */
  assessmentId: text("assessment_id"),

  /**
   * Foreign key to `controls.id` (optional).
   *
   * - Constraints: nullable.
   * - When populated, ties the evidence directly to a specific control row.
   *   This enables the platform to automatically update the control's `finding`
   *   status once evidence is approved (e.g. mark it `"in-place"`).
   * - Null when the request is raised without reference to a specific control
   *   (e.g. general audit documents, vendor certificates).
   */
  controlId: text("control_id"),

  /**
   * Denormalised framework control reference number (e.g. `"1.2.1"`, `"CC6.1"`).
   *
   * - Constraints: not null.
   * - Stored separately from `controlId` so the request can be displayed with its
   *   reference even if the control row is later deleted or the request is ad-hoc.
   * - Mirrors `controls.ref` when `controlId` is set.
   */
  controlRef: text("control_ref").notNull(), // "1.2.1"

  /**
   * Denormalised title of the related control, for display without a join.
   *
   * - Constraints: nullable.
   * - Populated at creation time from `controls.title` when `controlId` is set.
   * - Retained even if the control record is subsequently updated, providing
   *   a stable snapshot of the control's description at request-creation time.
   */
  controlName: text("control_name"),

  /**
   * Short code of the parent framework (e.g. `"PCI-DSS"`, `"SOC2"`).
   *
   * - Constraints: not null.
   * - Enables server-side filtering of evidence requests by compliance programme
   *   without joining to the `frameworks` or `controls` tables.
   */
  frameworkCode: text("framework_code").notNull(),

  /**
   * Full framework display name, denormalised for read-heavy UI queries.
   *
   * - Constraints: nullable.
   * - Examples: `"PCI DSS 4.0"`, `"SOC 2 Type II"`.
   * - Stored to avoid a join when rendering the evidence request list view.
   */
  frameworkName: text("framework_name"),

  /**
   * Foreign key to `entities.code`.
   *
   * - Constraints: not null.
   * - Evidence is always scoped to an entity so that each merchant's audit
   *   artefacts remain segregated — evidence gathered for Gopuff cannot be
   *   accidentally attributed to BevMo!'s compliance programme.
   */
  entityCode: text("entity_code").notNull(),

  /**
   * Short descriptive title of what evidence is being requested.
   *
   * - Constraints: not null.
   * - Examples: `"Q1 2025 Firewall Rule Export"`, `"Annual Pen Test Report"`.
   * - Shown as the headline in the evidence request list and notification emails.
   */
  title: text("title").notNull(),

  /**
   * Detailed instructions for the assignee explaining what artefact to provide
   * and in what format.
   *
   * - Constraints: nullable.
   * - Should specify: acceptable file formats, required date ranges, which system
   *   the export should come from, and any specific fields the QSA needs to see.
   * - Example: `"Export the current firewall ruleset from the PCI segment gateway
   *   (10.0.1.1) as a plain-text file.  Include both inbound and outbound rules."`
   */
  description: text("description"),

  /**
   * Workflow status tracking the evidence request through its lifecycle.
   *
   * - Constraints: not null, defaults to `"requested"`.
   * - Allowed values (see lifecycle diagram at the top of this file):
   *   - `"requested"`   — raised but not yet picked up by the assignee.
   *   - `"in-progress"` — assignee is actively gathering the evidence.
   *   - `"submitted"`   — assignee has uploaded / linked the artefact; awaiting review.
   *   - `"approved"`    — reviewer accepted the evidence as sufficient for the control.
   *   - `"rejected"`    — reviewer found the evidence insufficient; re-submission needed.
   */
  status: text("status").notNull().default("requested"), // requested|in-progress|submitted|approved|rejected

  /**
   * Priority level influencing how urgently the evidence must be collected.
   *
   * - Constraints: not null, defaults to `"medium"`.
   * - Allowed values: `"critical"` | `"high"` | `"medium"` | `"low"`.
   * - Critical evidence items may block the overall assessment from progressing;
   *   high-priority items have an impact on the assessment timeline.
   * - Drives UI sorting (critical/high items float to the top) and notification
   *   escalation rules.
   */
  priority: text("priority").notNull().default("medium"), // critical|high|medium|low

  /**
   * Username or display name of the person responsible for providing the evidence.
   *
   * - Constraints: nullable (not yet assigned when first created).
   * - Typically a control owner, system administrator, or team lead within the
   *   merchant entity.
   * - Receives email/in-app notifications about the request and due-date reminders.
   */
  assignee: text("assignee"),

  /**
   * Username or display name of the compliance team member who raised this request.
   *
   * - Constraints: nullable.
   * - Populated automatically from the authenticated session when the request is
   *   created via the UI.
   * - Used in the audit trail to attribute request creation to a specific person.
   */
  requestedBy: text("requested_by"),

  /**
   * ISO-8601 date (YYYY-MM-DD) by which the evidence must be submitted.
   *
   * - Constraints: nullable (may be TBD for newly raised requests).
   * - Due dates are coordinated with the overall assessment timeline; evidence
   *   submitted after this date may delay the assessment and AoC issuance.
   * - The platform surfaces overdue requests prominently in dashboards and
   *   sends escalation notifications as the deadline approaches.
   */
  dueDate: text("due_date"), // YYYY-MM-DD

  /**
   * Timestamp of when this evidence request was formally raised.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Distinct from `createdAt` to support future back-filling of historical
   *   requests that were originally tracked outside the platform.
   * - Used in the activity log and for SLA / time-to-close reporting.
   */
  requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),

  /**
   * Timestamp of when the evidence was formally approved by a reviewer.
   *
   * - Constraints: nullable; remains null until a reviewer accepts the submission.
   * - Set by application code when `status` transitions to `"approved"`.
   * - Used to calculate time-to-approval metrics and to populate the audit trail.
   */
  approvedAt: timestamp("approved_at", { withTimezone: true }),

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Distinct from `requestedAt` to support back-filling of records that were
   *   historically tracked in another system before migration.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `evidence_requests` insert payloads sent via the API.
 *
 * **Generated from** `evidenceRequestsTable` by `drizzle-zod`'s `createInsertSchema`.
 *
 * **Required fields** (caller must supply):
 *  - `id`            — UUID primary key.
 *  - `code`          — unique human-readable code (`EVR-YYYY-NNNN`).
 *  - `controlRef`    — control reference number (e.g. `"1.2.1"`).
 *  - `frameworkCode` — parent framework code (e.g. `"PCI-DSS"`).
 *  - `entityCode`    — owning entity code (e.g. `"gopuff"`).
 *  - `title`         — short descriptive title of the request.
 *
 * **Optional / defaulted fields**:
 *  - `status`      — defaults to `"requested"` if omitted.
 *  - `priority`    — defaults to `"medium"` if omitted.
 *  - `assessmentId`, `controlId`, `controlName`, `frameworkName`,
 *    `description`, `assignee`, `requestedBy`, `dueDate` — nullable; may be omitted.
 *  - `approvedAt`  — nullable; set by application logic on approval.
 *
 * **Omitted fields**:
 *  - `requestedAt` — handled by the database `defaultNow()`.
 *  - `createdAt`   — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertEvidenceSchema.parse({
 *   id: crypto.randomUUID(),
 *   code: "EVR-2026-0001",
 *   controlRef: "1.2.1",
 *   frameworkCode: "PCI-DSS",
 *   entityCode: "gopuff",
 *   title: "Firewall rule export – PCI segment",
 *   priority: "high",
 *   assignee: "alice@gopuff.com",
 *   dueDate: "2026-03-31",
 * });
 * await db.insert(evidenceRequestsTable).values(payload);
 * ```
 */
export const insertEvidenceSchema = createInsertSchema(evidenceRequestsTable).omit({ requestedAt: true, createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertEvidence` — shape of the object required to insert a new evidence request row.
 *
 * Inferred from `insertEvidenceSchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, evidence creation endpoints, test factories.
 *
 * @example
 * ```ts
 * async function createEvidenceRequest(body: InsertEvidence): Promise<EvidenceRequest> {
 *   const validated = insertEvidenceSchema.parse(body);
 *   const [row] = await db
 *     .insert(evidenceRequestsTable)
 *     .values(validated)
 *     .returning();
 *   return row;
 * }
 * ```
 */
export type InsertEvidence = z.infer<typeof insertEvidenceSchema>;

/**
 * `EvidenceRequest` — full shape of a row returned by a SELECT on `evidenceRequestsTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.  Includes all
 * columns (timestamps, nullable fields, and server-generated defaults).
 *
 * **Usage**: API response types, evidence panel component props, status dashboards,
 * export utilities.
 *
 * @example
 * ```ts
 * const openRequests: EvidenceRequest[] = await db
 *   .select()
 *   .from(evidenceRequestsTable)
 *   .where(
 *     and(
 *       eq(evidenceRequestsTable.entityCode, "bevmo"),
 *       inArray(evidenceRequestsTable.status, ["requested", "in-progress"]),
 *     ),
 *   );
 * ```
 */
export type EvidenceRequest = typeof evidenceRequestsTable.$inferSelect;
