/**
 * @file lib/db/src/schema/policies.ts
 * @description Schema for the **Policies** domain of the GRC data model.
 *
 * ## What is a Policy?
 * Policies are the organisation's internal written documents — information security
 * policies, procedures, standards, and guidelines — that formalise how controls
 * are implemented and maintained.  In a PCI DSS or SOC 2 audit, the QSA will
 * request policy documents as evidence that governance processes exist and are
 * documented.
 *
 * Examples of policy documents:
 *  - Information Security Policy (mandatory for PCI DSS Req 12.1)
 *  - Acceptable Use Policy
 *  - Incident Response Plan (PCI DSS Req 12.10)
 *  - Password / Authentication Policy (PCI DSS Req 8)
 *  - Change Management Procedure (PCI DSS Req 6.5)
 *  - Vendor Management Policy (PCI DSS Req 12.8)
 *
 * ## Policy lifecycle
 * ```
 * draft → current → review-due → overdue
 *                 ↘ retired
 * ```
 *  1. `draft`      — being authored; not yet approved or in effect.
 *  2. `current`    — approved and actively in force; reviewed within the required cycle.
 *  3. `review-due` — still in force but the scheduled review date has passed.
 *                    PCI DSS Requirement 12.1 mandates annual policy review.
 *  4. `overdue`    — significantly past the review date; escalation warranted.
 *  5. `retired`    — superseded or no longer applicable; preserved for audit history.
 *
 * ## Multi-framework, multi-entity design
 * A single policy document often satisfies requirements across multiple frameworks
 * (e.g. an Information Security Policy applies to both PCI DSS and SOC 2).
 * Similarly, a group-wide policy may apply to all three merchant entities.  The
 * `frameworks[]` and `entities[]` array columns capture these many-to-many
 * relationships without requiring a separate join table.
 *
 * ## Relationships
 *  - Many policies ←→ many Frameworks (via `frameworks[]` array of framework codes)
 *  - Many policies ←→ many Entities   (via `entities[]` array of entity codes)
 *  - Policies are referenced in EvidenceRequests as supporting governance documentation
 */

import { pgTable, text, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `policies` table — one row per internal governance / security policy document.
 */
export const policiesTable = pgTable("policies", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer.
   */
  id: text("id").primaryKey(),

  /**
   * Sequential human-readable policy identifier used in document headers and
   * compliance evidence packages.
   *
   * - Constraints: not null, unique.
   * - Format: `POL-NNN` e.g. `"POL-001"`, `"POL-015"`.
   * - Referenced in evidence requests (e.g. "Please provide POL-001 as evidence
   *   for PCI DSS Req 12.1.1").
   * - Must remain stable across policy versions — the same code is reused when
   *   a policy is revised; only the `version` field changes.
   */
  code: text("code").notNull().unique(), // POL-001

  /**
   * Full title of the policy document.
   *
   * - Constraints: not null.
   * - Examples: `"Information Security Policy"`, `"Incident Response Plan"`,
   *   `"Acceptable Use Policy"`.
   * - Used as the primary display label in policy lists and evidence packages.
   */
  name: text("name").notNull(),

  /**
   * Name of the policy owner — the role or individual accountable for maintaining
   * this document and ensuring it is reviewed on schedule.
   *
   * - Constraints: not null.
   * - Examples: `"CISO"`, `"Head of Compliance"`, `"Jane Smith"`.
   * - Policy ownership is explicitly required by PCI DSS Req 12.1.1 and SOC 2
   *   Trust Services Criteria CC2.1.
   */
  owner: text("owner").notNull(),

  /**
   * Document version string.
   *
   * - Constraints: not null.
   * - Examples: `"1.0"`, `"2.3"`, `"v4"`.
   * - Incremented each time the policy is substantively revised and re-approved.
   * - Minor editorial corrections may increment the minor version only (e.g. 1.0 → 1.1).
   * - Stored as text (not a semver object) for flexibility.
   */
  version: text("version").notNull(),

  /**
   * Lifecycle status of the policy.
   *
   * - Constraints: not null, defaults to `"current"`.
   * - Allowed values:
   *   - `"draft"`      — under authorship; not yet approved or in force.
   *   - `"current"`    — approved and actively in effect; up-to-date.
   *   - `"review-due"` — still in effect but past its scheduled review date.
   *                      PCI DSS Req 12.1 requires at least annual review.
   *   - `"overdue"`    — significantly past the review date; escalation warranted.
   *   - `"retired"`    — superseded or no longer applicable; retained for history.
   * - The compliance dashboard uses this to flag policies requiring attention.
   */
  status: text("status").notNull().default("current"), // draft|current|review-due|overdue|retired

  /**
   * ISO-8601 date (YYYY-MM-DD) when this version of the policy came into effect.
   *
   * - Constraints: nullable (drafts may not yet have an effective date).
   * - Marks when the policy was formally approved and began applying to the
   *   organisation.  May appear on the document cover page.
   */
  effectiveDate: text("effective_date"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) by which the policy must be reviewed and re-approved.
   *
   * - Constraints: nullable (set when the policy is published).
   * - PCI DSS Requirement 12.1 mandates that information security policies are
   *   reviewed at least once every 12 months and updated when the environment
   *   changes.
   * - The platform transitions `status` to `"review-due"` when this date passes,
   *   and to `"overdue"` after a configurable grace period.
   */
  reviewDate: text("review_date"), // YYYY-MM-DD

  /**
   * Total page count of the policy document.
   *
   * - Constraints: nullable (informational; not always known).
   * - Used in the policy detail view and evidence package summaries.
   * - Helps auditors quickly gauge whether the document is appropriately detailed.
   */
  pages: integer("pages"),

  /**
   * Array of framework codes indicating which compliance frameworks this policy
   * satisfies controls for.
   *
   * - Constraints: not null, defaults to `[]` (empty array).
   * - Examples: `["PCI-DSS"]`, `["PCI-DSS", "SOC2"]`, `["ISO27001"]`.
   * - Enables the compliance dashboard to show "N policies covering PCI-DSS"
   *   and to filter policies relevant to a specific framework.
   * - Stored as a PostgreSQL text array (not a join table) for simplicity;
   *   values must match `frameworks.code`.
   */
  frameworks: text("frameworks").array().notNull().default([]),

  /**
   * Array of entity codes indicating which merchant entities this policy applies to.
   *
   * - Constraints: not null, defaults to `[]` (empty array).
   * - Examples: `["gopuff", "bevmo", "liquorbarn"]` (group-wide policy),
   *   `["bevmo"]` (BevMo!-specific retail policy).
   * - Enables entity-scoped policy filtering: the Gopuff compliance dashboard
   *   only shows policies that include `"gopuff"` in this array.
   * - Values must match `entities.code`.
   */
  entities: text("entities").array().notNull().default([]),

  /**
   * Brief narrative summary of the policy's scope and purpose.
   *
   * - Constraints: nullable.
   * - Displayed on the policy detail card to give reviewers a quick sense of
   *   what the document covers without opening the full PDF.
   */
  description: text("description"),

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `policies` insert payloads sent via the API.
 *
 * **Generated from** `policiesTable` by `drizzle-zod`'s `createInsertSchema`.
 * Array columns (e.g. `frameworks`, `entities`) are validated as `z.array(z.string())`.
 *
 * **Required fields** (caller must supply):
 *  - `id`      — UUID primary key.
 *  - `code`    — unique human-readable code (`POL-NNN`).
 *  - `name`    — full document title.
 *  - `owner`   — accountable owner (role or person name).
 *  - `version` — document version string.
 *
 * **Optional / defaulted fields**:
 *  - `status`        — defaults to `"current"` if omitted.
 *  - `frameworks`    — defaults to `[]`; provide an array of framework codes.
 *  - `entities`      — defaults to `[]`; provide an array of entity codes.
 *  - `effectiveDate` — nullable; set when the policy is approved.
 *  - `reviewDate`    — nullable; set at publication time.
 *  - `pages`         — nullable; set if the page count is known.
 *  - `description`   — nullable; provide a summary if available.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertPolicySchema.parse({
 *   id: crypto.randomUUID(),
 *   code: "POL-001",
 *   name: "Information Security Policy",
 *   owner: "CISO",
 *   version: "3.0",
 *   status: "current",
 *   effectiveDate: "2025-01-01",
 *   reviewDate: "2026-01-01",
 *   frameworks: ["PCI-DSS", "SOC2"],
 *   entities: ["gopuff", "bevmo", "liquorbarn"],
 * });
 * await db.insert(policiesTable).values(payload);
 * ```
 */
export const insertPolicySchema = createInsertSchema(policiesTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertPolicy` — shape of the object required to insert a new policy row.
 *
 * Inferred from `insertPolicySchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, policy creation endpoints, seed scripts.
 *
 * @example
 * ```ts
 * async function createPolicy(body: InsertPolicy): Promise<Policy> {
 *   const validated = insertPolicySchema.parse(body);
 *   const [row] = await db.insert(policiesTable).values(validated).returning();
 *   return row;
 * }
 * ```
 */
export type InsertPolicy = z.infer<typeof insertPolicySchema>;

/**
 * `Policy` — full shape of a row returned by a SELECT on `policiesTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, policy list components, evidence package exports.
 *
 * @example
 * ```ts
 * const overdue: Policy[] = await db
 *   .select()
 *   .from(policiesTable)
 *   .where(eq(policiesTable.status, "overdue"));
 * ```
 */
export type Policy = typeof policiesTable.$inferSelect;
