/**
 * @file lib/db/src/schema/vendors.ts
 * @description Schema for the **Vendors** domain of the GRC data model.
 *
 * ## What is a Vendor (TPSP)?
 * "Vendors" in this system are Third-Party Service Providers (TPSPs) — external
 * companies whose products or services interact with, or could materially impact,
 * the organisation's Cardholder Data Environment (CDE) or broader information
 * security posture.
 *
 * ## PCI DSS requirement
 * PCI DSS Requirement 12.8 mandates that merchants:
 *  - Maintain a list of all TPSPs that handle or could affect the security of
 *    cardholder data.
 *  - Have a written agreement with each TPSP acknowledging their PCI DSS obligations.
 *  - Monitor each TPSP's PCI DSS compliance status at least annually.
 *  - Have a programme to respond to TPSP compliance failures.
 *
 * This table is the platform's implementation of that TPSP register.
 *
 * ## Risk classification
 * Vendors are assigned a risk level (`critical` → `low`) based on their access
 * to and potential impact on cardholder data.  The risk level drives:
 *  - Review frequency (critical vendors reviewed quarterly; low-risk vendors annually).
 *  - The depth of due diligence required (e.g. shared responsibility matrix, SOC 2
 *    report review, on-site audit).
 *  - Escalation priority when a vendor's PCI certification is approaching expiry.
 *
 * ## Vendor certification tracking
 * `hasPciCertification` and `certificationExpiry` allow the platform to track
 * whether each TPSP holds its own PCI DSS certification and when that expires.
 * A certified TPSP reduces the merchant's audit burden for controls that are
 * fully delegated to that provider (the TPSP's AoC provides evidence for those
 * controls).
 *
 * ## Relationships
 *  - Many vendors ←→ many Entities (via `entities[]` array of entity codes)
 *  - Vendors may be referenced in EvidenceRequests as third-party compliance artefacts
 *    (e.g. "provide the vendor's latest AoC")
 */

import { pgTable, text, boolean, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

/**
 * `vendors` table — one row per third-party service provider in the TPSP register.
 */
export const vendorsTable = pgTable("vendors", {
  /**
   * UUID primary key.
   *
   * - Constraints: primary key, text, not null (implicit for PK).
   * - Generated by the application layer.
   */
  id: text("id").primaryKey(),

  /**
   * Vendor company name as it appears in contracts and the TPSP register.
   *
   * - Constraints: not null.
   * - Examples: `"Stripe"`, `"Amazon Web Services"`, `"Rapid7"`, `"Okta"`.
   * - Used as the primary display label in the vendor list and evidence requests.
   */
  name: text("name").notNull(),

  /**
   * Category of service provided by this vendor.
   *
   * - Constraints: not null.
   * - Used for risk classification, filtering, and reporting by service type.
   * - Common categories:
   *   - `"Payment Processing"` — directly handles PANs or transaction data (highest risk).
   *   - `"Cloud Infrastructure"` — hosts CDE systems (e.g. AWS, GCP, Azure).
   *   - `"Penetration Testing"` — authorised to attack CDE systems.
   *   - `"Identity & Access Management"` — controls authentication to CDE systems.
   *   - `"Security Operations"` — monitors for threats in or around the CDE (SOC/SIEM).
   *   - `"Managed Security Services"` — outsourced security functions.
   *   - `"Network Services"` — provides network connectivity or segmentation.
   *   - `"Scanning Vendor (ASV)"` — PCI SSC-approved scanning vendor for quarterly scans.
   */
  serviceType: text("service_type").notNull(),

  /**
   * Free-text description of what the vendor does and how they interact with the CDE.
   *
   * - Constraints: nullable.
   * - Should document the specific service used, which CDE systems it touches, and
   *   why the vendor is included in the TPSP register.
   * - Example: `"AWS hosts the PCI-scoped payment processing workloads in the
   *   us-east-1 region.  The shared responsibility model applies."`
   */
  description: text("description"),

  /**
   * Inherent risk level assigned to this vendor based on CDE access and impact.
   *
   * - Constraints: not null, defaults to `"medium"`.
   * - Allowed values:
   *   - `"critical"` — vendor has direct access to PANs, CVVs, or core payment
   *                    infrastructure (e.g. payment processor, HSM vendor).
   *   - `"high"`     — vendor has significant access to systems within or
   *                    directly connected to the CDE (e.g. cloud hosting provider).
   *   - `"medium"`   — vendor has indirect or limited CDE exposure (e.g. SIEM
   *                    that ingests CDE logs).
   *   - `"low"`      — no meaningful CDE interaction (e.g. marketing analytics,
   *                    HR SaaS).
   * - Drives review frequency and due-diligence depth.
   */
  riskLevel: text("risk_level").notNull().default("medium"), // critical|high|medium|low

  /**
   * Current engagement status of this vendor relationship.
   *
   * - Constraints: not null, defaults to `"active"`.
   * - Allowed values:
   *   - `"active"`       — vendor is currently engaged and under active management.
   *   - `"inactive"`     — vendor relationship has ended; row retained for history.
   *   - `"under-review"` — new vendor undergoing onboarding due diligence, or existing
   *                        vendor being re-evaluated due to a risk event.
   */
  status: text("status").notNull().default("active"), // active|inactive|under-review

  /**
   * Array of entity codes identifying which merchant brands engage this vendor.
   *
   * - Constraints: not null, defaults to `[]`.
   * - Examples:
   *   - `["gopuff", "bevmo", "liquorbarn"]` — group-wide vendor used by all brands.
   *   - `["bevmo"]` — vendor engaged only by BevMo! (e.g. a brand-specific POS vendor).
   * - Values must match `entities.code`.
   * - Enables entity-scoped TPSP filtering in the vendor management views.
   */
  entities: text("entities").array().notNull().default([]),

  /**
   * Primary point-of-contact name at the vendor for compliance and security matters.
   *
   * - Constraints: nullable.
   * - PCI DSS Req 12.8.4 requires the merchant to maintain contact information
   *   for their TPSP contacts.
   * - Used when the compliance team needs to request the vendor's current AoC,
   *   a penetration test attestation, or a vulnerability remediation status.
   */
  contactName: text("contact_name"),

  /**
   * Email address for the vendor's compliance or security contact.
   *
   * - Constraints: nullable.
   * - Used for AoC renewal requests, incident notifications, and annual
   *   compliance review outreach.
   */
  contactEmail: text("contact_email"),

  /**
   * ISO-8601 date (YYYY-MM-DD) of the most recent compliance review for this vendor.
   *
   * - Constraints: nullable (new or never-reviewed vendors will have null).
   * - PCI DSS Requirement 12.8.3 mandates that the organisation monitors its
   *   TPSPs' PCI DSS compliance status at least annually.
   * - Used to calculate "days since last review" and flag overdue reviews.
   */
  lastReviewDate: text("last_review_date"), // YYYY-MM-DD

  /**
   * ISO-8601 date (YYYY-MM-DD) when the next scheduled compliance review of this
   * vendor is due.
   *
   * - Constraints: nullable.
   * - Typically `lastReviewDate + 12 months` for medium/low risk; shorter cycles
   *   for critical/high-risk vendors.
   * - The platform generates review-due alerts as this date approaches.
   */
  nextReviewDate: text("next_review_date"), // YYYY-MM-DD

  /**
   * Whether this vendor holds its own current PCI DSS certification.
   *
   * - Constraints: not null, defaults to `false`.
   * - A vendor listed as a Level-1 Service Provider on Visa's or Mastercard's
   *   Global Registry of Service Providers holds their own AoC.
   * - When `true`, the merchant can obtain the vendor's AoC as evidence for
   *   controls delegated to that TPSP, reducing the merchant's own assessment scope.
   * - When `false`, the merchant is responsible for assessing those controls.
   */
  hasPciCertification: boolean("has_pci_certification").notNull().default(false),

  /**
   * ISO-8601 date (YYYY-MM-DD) when the vendor's PCI DSS certification expires.
   *
   * - Constraints: nullable.
   * - Meaningful only when `hasPciCertification = true`.
   * - PCI SSC-registered service provider certifications are valid for 12 months.
   * - The platform surfaces expiry alerts so the merchant can request the vendor's
   *   renewed AoC before the current one lapses.
   * - A lapsed vendor certification may increase the merchant's own assessment
   *   scope until the vendor renews.
   */
  certificationExpiry: text("certification_expiry"), // YYYY-MM-DD

  /**
   * Free-text notes about the vendor relationship, risk exceptions, or review outcomes.
   *
   * - Constraints: nullable.
   * - Examples: risk acceptance notes, CCW references, contact history, escalations.
   * - Visible to the compliance team; not shared in external reports.
   */
  notes: text("notes"),

  /**
   * Row creation timestamp, stored with time zone.
   *
   * - Constraints: not null, defaults to `now()` at insert time.
   * - Immutable after insert — never update this column.
   */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// Zod insert schema
// ---------------------------------------------------------------------------

/**
 * Zod schema for validating `vendors` insert payloads sent via the API.
 *
 * **Generated from** `vendorsTable` by `drizzle-zod`'s `createInsertSchema`.
 * Array columns (e.g. `entities`) are validated as `z.array(z.string())`.
 * Boolean columns (e.g. `hasPciCertification`) are validated as `z.boolean()`.
 *
 * **Required fields** (caller must supply):
 *  - `id`          — UUID primary key.
 *  - `name`        — vendor company name.
 *  - `serviceType` — category of service (e.g. `"Payment Processing"`).
 *
 * **Optional / defaulted fields**:
 *  - `riskLevel`           — defaults to `"medium"` if omitted.
 *  - `status`              — defaults to `"active"` if omitted.
 *  - `entities`            — defaults to `[]`; provide array of entity codes.
 *  - `hasPciCertification` — defaults to `false` if omitted.
 *  - `description`         — nullable.
 *  - `contactName`         — nullable.
 *  - `contactEmail`        — nullable.
 *  - `lastReviewDate`      — nullable.
 *  - `nextReviewDate`      — nullable.
 *  - `certificationExpiry` — nullable.
 *  - `notes`               — nullable.
 *
 * **Omitted fields**:
 *  - `createdAt` — handled by the database `defaultNow()`.
 *
 * @example
 * ```ts
 * const payload = insertVendorSchema.parse({
 *   id: crypto.randomUUID(),
 *   name: "Stripe",
 *   serviceType: "Payment Processing",
 *   riskLevel: "critical",
 *   entities: ["gopuff", "bevmo", "liquorbarn"],
 *   hasPciCertification: true,
 *   certificationExpiry: "2026-04-30",
 *   contactEmail: "security@stripe.com",
 * });
 * await db.insert(vendorsTable).values(payload);
 * ```
 */
export const insertVendorSchema = createInsertSchema(vendorsTable).omit({ createdAt: true });

// ---------------------------------------------------------------------------
// TypeScript types
// ---------------------------------------------------------------------------

/**
 * `InsertVendor` — shape of the object required to insert a new vendor row.
 *
 * Inferred from `insertVendorSchema` (the Zod insert schema).
 *
 * **Usage**: API request body validation, vendor onboarding endpoints, seed scripts.
 *
 * @example
 * ```ts
 * async function addVendor(body: InsertVendor): Promise<Vendor> {
 *   const validated = insertVendorSchema.parse(body);
 *   const [row] = await db.insert(vendorsTable).values(validated).returning();
 *   return row;
 * }
 * ```
 */
export type InsertVendor = z.infer<typeof insertVendorSchema>;

/**
 * `Vendor` — full shape of a row returned by a SELECT on `vendorsTable`.
 *
 * Inferred from the Drizzle table definition via `$inferSelect`.
 *
 * **Usage**: API response types, TPSP register views, vendor risk dashboards,
 * certification expiry alert jobs.
 *
 * @example
 * ```ts
 * // Find all critical vendors with expiring certifications
 * const expiring: Vendor[] = await db
 *   .select()
 *   .from(vendorsTable)
 *   .where(
 *     and(
 *       eq(vendorsTable.riskLevel, "critical"),
 *       eq(vendorsTable.hasPciCertification, true),
 *       lte(vendorsTable.certificationExpiry, thirtyDaysFromNow),
 *     ),
 *   );
 * ```
 */
export type Vendor = typeof vendorsTable.$inferSelect;
